#! /usr/bin/env python

# Audio Logger, a program that logs audio form the soundcard with 
# a set of useful features.
# Copyright (C) 2010, 2011 Gareth Andrew Lloyd
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public 
# License along with this program; if not, write to the Free 
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor, 
# Boston, MA  02110-1301, USA.

import logger
from sys import stdout

if __name__ == "__main__":
  stdout.write("""\
Audio Logger Pre-Alpha
Copyright (C) 2010, 2011 Gareth Andrew Lloyd
Audio Logger comes with ABSOLUTELY NO WARRANTY.  This is free 
software, and you are welcome to redistribute it under certain
conditions. For full information see the GPLv2 licence online.

""")

  try:
    l = logger.Logger(chunkseconds=5, logmaxage=60)
    l.run()
  except KeyboardInterrupt:
    print('KeyboardInterrupt')
